name: cmnext
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - _libgcc_mutex
  - _openmp_mutex
  - _pytorch_select
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cudatoolkit
  - cudnn
  - ffmpeg
  - freetype
  - future
  - gmp
  - gnutls
  - intel-openmp
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libffi
  - libgcc-ng
  - libgomp
  - libiconv
  - liblapack
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtiff
  - libuv
  - libwebp-base
  - lz4-c
  - magma
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nccl
  - ncurses
  - nettle
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openh264
  - openjpeg
  - openssl
  - pillow
  - pycparser
  - python
  - python_abi
  - pytorch
  - pytorch-gpu
  - pytorch-mutex
  - readline
  - six
  - sleef
  - sqlite
  - tk
  - torchaudio
  - torchvision
  - typing_extensions
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - absl-py
    - addict
    - argon2-cffi
    - argon2-cffi-bindings
    - asttokens
    - attrs
    - backcall
    - bleach
    - cachetools
    - charset-normalizer
    - cycler
    - dataclasse
    - debugpy
    - decorator
    - defusedxml
    - descartes
    - easydict
    - einops
    - entrypoints
    - executing
    - fire
    - fvcore
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - idna
    - importlib-metadata
    - importlib-resources
    - iopath
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - joblib
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - kiwisolver
    - markdown
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mistune
    - mmcv-full
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - nuscenes-devkit
    - oauthlib
    - opencv-python
    - packaging
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - plyfile
    - portalocker
    - prometheus-client
    - prompt-toolkit
    - protobuf
    - ptyprocess
    - pure-eval
    - pyasn1
    - pyasn1-modules
    - pycocotools
    - pygments
    - pyparsing
    - pyquaternion
    - pyrsistent
    - python-dateutil
    - pyyaml
    - pyzmq
    - qtconsole
    - qtpy
    - requests
    - requests-oauthlib
    - rsa
    - scikit-learn
    - scipy
    - send2trash
    - setuptools
    - shapely
    - stack-data
    - tabulate
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - tensorboardx
    - termcolor
    - terminado
    - testpath
    - threadpoolctl
    - timm
    - tornado
    - tqdm
    - traitlets
    - urllib3
    - wcwidth
    - webencodings
    - werkzeug
    - wheel
    - widgetsnbextension
    - yacs
    - yapf
    - zipp
